### ISSUE TITLE
Question: Random access supported by specification?

### ISSUE THREAD

**Issue by donatello** [minio/sio#12] opened 2017-10-31 15:16 UTC
The Readme states that random access is a property of this encryption format - however, the specification at https://github.com/minio/sio/blob/master/DARE.md is not very clear about this.

For random access to work, we need the payload size in each package sequence of an encrypted file to be constant (except for the last one, which may be smaller). However this does not seem to be required by the specification. While the `sio` implementation uses a fixed payload size (that can be configured at the beginning) to generate the packages - other implementations may use different package sizes within the same package sequence - this would appear to still be specification compliant - but it defeats the goal of efficient random access.

**Comment by aead** [comment] 2017-10-31 19:11
In general correct. Random access is treated as kind of a 'feature' which must be known (as requirement) in advance. The problem is:
If the package size is fixed to e.g. 64 KB all blocks will be multiple of 64 KB even if just one byte is encrypted. A variable package size has exactly the issue you described.
If random access is required two different solutions are possible:
1. The number of packages is somehow recorded and saved as part of the file - That's the most flexible but also quite complicated solution.
2. The package size is basically restricted to one fixed value (expect for the last package) - As you mentioned the implementation does this by default. Then it's possible to calculate the offset of each package and decrypt each package by random access. Of course this approach does not work if data is appended after the last block -> different package sizes in one sequence. 

Unfortunately I don't see a way to provide random access in the general case and being efficient for small data as well as avoiding external metadata.

**Comment by harshavardhana** [comment] 2017-10-31 21:21
> But I see that it's actually one of the most important use cases.

Why is this an important use case? - At best its a corner case no one is really interested IMO in making each blocks randomized unless you are writing some sort of a encrypted block device with journal-ling of each such blocks.

Also @donatello what is the requirement in this scenario?

**Comment by aead** [comment] 2017-10-31 21:57
The use case I'm talking about is random access for the "simple" case:
1. Encrypt file
2. Decrypt file from offset `off` to length `len`
Currently the offset and length calculation (and slicing of the requested range) must be implemented by the client -> That can be tricky...

I agree with you @harshavardhana - The case where length of different blocks within one sequence is arbitrary AND random access is required is kind of a rare corner case, I guess...

**Comment by harshavardhana** [comment] 2017-10-31 23:50
> Decrypt file from offset off to length len
> Currently the offset and length calculation (and slicing of the requested range) must be implemented by the client -> That can be tricky...

This we have to do @aead

**Comment by donatello** [comment] 2017-11-01 08:39
> Why is this an important use case? - 
> Also @donatello what is the requirement in this scenario?

@harshavardhana 
Random access would be an important differentiating feature for an encrypted file format as it would allow decrypting parts of the file with little overhead - range requests can be served with low time-to-first-byte.

The spec should treat this as an important feature - it differentiates it from older more established formats (e.g. AESCrypt - https://www.aescrypt.com/aes_file_format.html and OpenPGP - https://tools.ietf.org/html/rfc4880).

IMO, the specification should require the size of packages to be constant and perhaps specified in the beginning, so that it need not be repeated per-package and offset-length calculations are straightforward (I am not sure why you/we are opposed to package sequence common metadata). The current specification would allow variable package sizes - this is a problem for interoperability - if we intend that a client-encrypted DARE file is stored on a server, and the server is asked to decrypt parts of it (given the secret key) and return the resulting data, it cannot do so without inspecting the sizes of the packages (this is slow), as they are not guaranteed (by the spec) to be constant. A client encryption tool would only be required to create valid DARE package sequences (i.e. it is not possible to restrict the implementations being used).

> I agree with you @harshavardhana - The case where length of different blocks within one sequence is arbitrary AND random access is required is kind of a rare corner case, I guess...

I would even say this case is not required to be supported - that packages with different sizes be permitted in the same package sequence.

**Comment by aead** [comment] 2017-11-02 16:29
@donatello 
Fixing the package size to a fixed value has some issue.
- Short messages will be extended to at least one package - depending on the use case that's not acceptable (e.g. if many small files must be encrypted)
This could be fixed specifying that the package size is arbitrary (up to 64 KB) but must be the same within one sequence of packages. So the first package fixes the package size of the hole sequence.
Unfortunately this is also no good solution:
 - Appending packages to a sequence with a very small first package causes significant overhead.
 - For random access the package size must be known in advance - it could be extracted by reading the first package but this also moves complexity to the applications...

- Appending of encrypted data requires reading at least one package (expect the package size is remembered by the application)

Currently the behavior is:
Every sequence which can be decrypted successfully by random access is a valid encrypted sequence.  The other way around - every valid encrypted sequence can be decrypted successfully by random access - is not true. The problem here are two conflicting requirements:
 - 'easy' random access 
- small overhead for all messages
The current specification prefers the later over the first point. However random access is possible if required but therefore some restrictions must be accepted: As you mentioned it's not possible to decrypt an arbitrary (but valid) encrypted sequence by random access.
 
About the external metadata.
I tried to avoid external metadata to keep the format suitable for many different use cases. E.g.
imagine a file encryption tool would encrypt a file and create an additional metadata file. Now you have to ensure that:
 - The metadata file does not reveal information and cannot be modified (this is of course possible)
 - The metadata is always available when the file should be decrypted.
 
Further the users must always specify the correct(!) metadata for a given file and you double the number of files - imagine you encrypt 10000 files -> you end up with 20000.
External metadata introduces several new ways how things could go wrong... 

Of course there are many ways to work around this issues. For example if the sequence common metadata is not that complex you can store it as a "sequence header/tailer". Unfortunately you have to do 2 read operations all the time. Depending on the use case that's maybe affordable. It's basically a tread-off.

>  if we intend that a client-encrypted DARE file is stored on a server, and the server is asked to decrypt parts of it (given the secret key) and return the resulting data, it cannot do so without inspecting the sizes of the packages (this is slow), as they are not guaranteed (by the spec) to be constant.

This is actually a very good point 👍 I didn't thought about that. Luckily we (harsha and ab) decided to follow AWS S3 precisely - so client and server side encryption will be separated. That won't be an issue.

I see that random access is a important use case and the implementation **must** support it but I don't think we need to restrict other requirements for it. Of course we have to make it explicit how to use random access and explain when it works and when it doesn't.

BTW the linked tools also don't provide a "tamper-proof" encryption (especially open-pgp) and there is no possibility to verify the integrity of ranges.

**Comment by aead** [comment] 2017-11-08 13:08
#13

**Comment by aead** [comment] 2017-11-09 22:57
@donatello Closing this. If you've any further question, please reopen.

**Closed by aead** 2017-11-09 22:57 UTC
Labels: question
